// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF27FfXhVCpKWSkfPBoQQQJ7JcNoqrMhw',
    appId: '1:71920747656:web:9fa45ef0f54e31115b0b3d',
    messagingSenderId: '71920747656',
    projectId: 'buildmaster-project',
    authDomain: 'buildmaster-project.firebaseapp.com',
    storageBucket: 'buildmaster-project.appspot.com',
    measurementId: 'G-MTDHZHMCKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj-qeMz97NzpV95sJLFvupmCJ5j_0WZG4',
    appId: '1:71920747656:android:3c44e43637be2bfa5b0b3d',
    messagingSenderId: '71920747656',
    projectId: 'buildmaster-project',
    storageBucket: 'buildmaster-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqUXZxNVLbZmhgoEsoGeirB1mkRt8xdJI',
    appId: '1:71920747656:ios:2c0769c718aaabf65b0b3d',
    messagingSenderId: '71920747656',
    projectId: 'buildmaster-project',
    storageBucket: 'buildmaster-project.appspot.com',
    iosClientId: '71920747656-t5glp593ledb94g4oujdaed1iq5tjprm.apps.googleusercontent.com',
    iosBundleId: 'com.example.buildmasterRev1',
  );
}
